PREFIX ex: <http://example.org/nswi144/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?country ?countryLabel ?countryCode
WHERE {
    ?country rdf:type ex:Country ;
            skos:prefLabel ?countryLabel ;
            ex:countryCode ?countryCode .
}
ORDER BY ASC (?countryLabel)